version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./data:/app/data
    command: npm run start
    ports:
      - 19999:19999
    environment:
      - PORT=19999
      - WEBAPP_PORT=19999
