version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./data:/app/data
    command: npm run start
    ports:
      - 29999:29999
    environment:
      - PORT=29999
      - WEBAPP_PORT=29999
